#description
#
#device name: [[joint0 (knee), joint1 (hip), check for button] ,...]
#

kinematics_extend:
  leg1: [[0x08AA, 0x04C0, True]]
  leg2: [[0x0744, 0x04D0, True]]
  leg3: [[0x08AA, 0x04AE, True]]
  
kinematics_retract:
  leg1: [[0x08AA, 0x04C0],[0x0398, 0x04C0]]
  leg2: [[0x0744, 0x04D0],[0x0218, 0x04D0]]
  leg3: [[0x08AA, 0x04AE],[0x03BD, 0x04AE]]
